name: trigger jenkins build
on:
  pull_request:
    types: [ closed ]
      
jobs:

  build:
    name: Build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://0217-176-185-241-122.eu.ngrok.io"
        user: "admin"
        token: "113911baecc7efc033a72e49df11d9f847"
        job: "ecoshop-webapp"
