name: trigger jenkins tests to validate open MR

on:
  pull_request:
      branches:
        - main
      types: [opened]
      
jobs:

  validate:
    name: Validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.JS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: npm install test
      run: |
        npm i
        npm run test
      env:
        CI: true
